### ISSUE TITLE
Database Project/Stored Procedures/dbo.dbasp_maintenance_shrinklog.sql

### ISSUE THREAD

**Issue by amin-mazidi** [SiavashGolchoobian/SqlDeep#2]
When the backup process for large databases takes a long time, and during this time a stored procedure (dbasp_maintenance_shrinklog) is executed, the following error occurs : 

file manipulation operations (such as ALTER DATABASE ADD FILE) and encryption changes on a database must be serialized. 
**Reissue the statement after the current backup or file manipulation operation is completed**

please before shrink log ,check backup is running on current database  or not. if backup is running, current database' log does not shrink.

thanks

**Comment by SiavashGolchoobian** [comment]
this issue was resolved by adding backup process control before shrinking the file.
